variables:
  GIT_DEPTH: 10
  GIT_STRATEGY: clone
  REGISTRY: gitlab.manytask.org:5050/python/public-2025-fall
  REF_DIR: /opt/shad

# Testing and Grading all changed tasks
grade:
  image: $REGISTRY/testenv:latest
  rules:
    - if: $CI_PROJECT_NAME =~ /^public-(fall|spring)-20\d\d/
      when: never
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /contributing/ || $CI_COMMIT_BRANCH =~ /contributing/
      when: never
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: on_success
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: on_success
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: manual
    - when: on_success
  script:
    - cp /opt/shad/.checker.yml $CI_PROJECT_DIR
    - cp /opt/shad/.manytask.yml $CI_PROJECT_DIR
    - python -m checker grade
      --username $GITLAB_USER_LOGIN
      --submit-score
      -- $CI_PROJECT_DIR $REF_DIR


# Checking contribution to the main repo
check:
  image: $REGISTRY/testenv:latest
  rules:
    - if: $CI_PROJECT_NAME =~ /^public-(fall|spring)-20\d\d/
      when: never
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /contributing/ || $CI_COMMIT_BRANCH =~ /contributing/
      when: on_success
    - when: never
  script:
    - echo "Using reference dir = ${REF_DIR:-/opt/shad}"
    - '[ -d "${REF_DIR:-/opt/shad}" ] || { echo "ERROR: Reference dir ${REF_DIR:-/opt/shad} not found in image" >&2; exit 1; }'
    - cp "${REF_DIR:-/opt/shad}/.checker.yml" "$CI_PROJECT_DIR"
    - cp "${REF_DIR:-/opt/shad}/.manytask.yml" "$CI_PROJECT_DIR"
    - python -m checker grade -- "$CI_PROJECT_DIR" "${REF_DIR:-/opt/shad}"
  timeout: 30 minutes
